// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface ISchemaDefinition {
    name:       string;
    schema:     ISchema[];
    appId:      string;
    parserType: string;
}

export interface ISchema {
    attributePath: string;
    actionType:    string;
    convertInfo?:  IConvertInfo;
    event?: ISchemaEvent;
}

export interface IConvertInfo {
    functionType: string;
    parameters?:  string[];
}

export interface ISchemaEvent {
    name:         string;
    typeCode:     number;
    unit:         string;
}
