// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface SchemaDefinition {
    name:       string;
    schema:     Schema[];
    appId:      string;
    parserType: string;
}

export interface Schema {
    attributePath: string;
    actionType:    string;
    convertInfo?:  ConvertInfo;
    name?:         string;
    typeCode?:     number;
    unit?:         string;
}

export interface ConvertInfo {
    functionType: string;
    parameters?:  string[];
}
