language: nodejs
before_script:
  - npm run lint
  - npm run build
script:
  - npm run test
deploy:
  - provider: npm
    skip_cleanup: true
    email: 'shakeda@axonize.com'
    api_key: $NPM_TOKEN
    on:
      tags: true
